---
toc: false 
---

## Formålet med undersøgelsen 
Vi ved, at en del af de mennesker, som får type 2-diabetes i en ung alder, har en genetisk form for diabetes. Disse behandles lidt anderledes end type 2-diabetes, og det er derfor vigtigt at finde ud af, hvem vi skal teste genetisk, så de får den rigtige behandling. Det ser også ud til, at dem der får diabetes som yngre har en anderledes profil end dem, der får det som ældre. Det vil vi gerne undersøge nærmere for at kunne lave optimale vejledninger for behandling og opfølgning.

Det primære formål er at gennemføre en omfattende klinisk karakterisering af personer med tidlig opstået type 2 diabetes. Vi vil gerne blive klogere på, hvordan type 2-diabetes udvikler sig hos yngre personer. Ved at samle viden om blandt andet kroppens funktioner, arvelige forhold, mundsundhed og trivsel håber vi at kunne forstå sygdommen bedre. Den viden kan på sigt være med til at forbedre behandling og forebygge komplikationer. 

## Undersøgelsen er en del af projekt 2EARLY  
Heldbredsundersøgelsen er en del af et større projekt, som har til formål at arbejde bredt med emnet *early-onset type 2 diabetes -EOT2D *.

Traditionelt har type 2-diabetes været betragtet som en sygdom, der primært ramte ældre mennesker. I de senere årtier er der imidlertid sket en markant stigning i antallet af personer, som udvikler sygdommen før 40-årsalderen. 



