---
toc: false
---

## Hvad får jeg ud af at deltage 
* Du får en grundig undersøgelse af din diabetes og sundhed
* Resultaterne deles med din læge
* Du hjælper med vigtig forskning, der kan være med til at forbedre behandling og forebygge komplikationer hos yngre voksne med type 2-diabetes


## Hvad skal jeg gøre før forsøgsdagen

Indsæt noget tekst 

## Hvordan forløber forsøgsdagen

Skriv hvor lægne undersøgelsen varer?  
Du vil få lavet følgende undersøgelser på forsøgsdagen: 

**Målinger**

* Højde, vægt og taljemål
* Blodtryk og puls
* Håndstyrke

**Prøver** 

* Blodprøve (fx blodsukker, kolesterol, evt  gentest mm)
* Urinprøve
* Afføringsprøve
* Spytprøve

**Scanning og undersøgelse**

* Ultralyd af leveren for at undersøge fedtindholdet og tegn på skrumpelever
* Tandundersøgelse (som et tjek hos tandlægen men uden behandling)

**Spørgeskemaer** (kan også udfyldes hjemmefra) 

* Om dit helbred
* Om dit mentale velvære
* Om hvordan diabetes påvirker dit liv

## Hvad sker der efter forsøgsdagen
Du vil blive kontaktet af en læge fra Steno Diabetes Center Aarhus, som vil forklare resultaterne fra forsøgsdagen og evt. give anbefalinger. 

Hvis du ønsker det, så sender Steno Diabetes Center Aarhus et brev med resultaterne fra forsøgsdagen til:

* din egen læge eller diabeteslæge 
* din tandlæge 

Efter forsøget er det fortsat din egen læge/diabeteslæge der står for din diabetesbehandling. 
